=== asc0ltato/KYAR-1sem/Лабы/лаба 12/3.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs ="http://www.w3.org/2001/XMLSchema">
<xs:element name="account">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="surname" type="xs:string"/>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="patronymic" type="xs:string"/>
            <xs:element name="date_of_birth" type="xs:string"/>
            <xs:element name="country" type="xs:string"/>
            <xs:element name="city" type="xs:string"/>
            <xs:element name="telephone" type="xs:string"/>
            <xs:element name="email" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
</xs:element>
</xs:schema>

=== asc0ltato/KYAR-1sem/Лабы/лаба 12/zad3.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="style.css"?>

<account xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="3.xsd">
    <surname>Жук</surname>
    <name>Светлана</name>
    <patronymic>Сергеевна</patronymic>
    <date_of_birth>20.10.2004</date_of_birth>
    <country>Belarus</country>
    <city>Minsk</city>
    <telephone> +375259265072</telephone>
    <email>superpando4ka@gmail.com</email>
</account>
